## chart: https://github.com/qlik-trial/bonjour-world/tree/master/manifests/bonjour-world/chart/bonjour-world

{{ $environment := getenv "ENVIRONMENT" "unknown" -}}
{{ $region := getenv "REGION" "localregion" -}}
{{ $registry := getenv "CONTAINER_REGISTRY_URL" "" -}}
{{- $provider := getenv "PROVIDER" "aws" }}

image:
  registry: {{ $registry }}
  repository: bonjour-world
  pullPolicy: Always

replicaCount: 1
arguments:
  - --sleep-secs
  - "2000"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetAverageUtilizationMemory: 80

deployment:
  annotations:
    dynatrace.com/inject: "false"
    oneagent.dynatrace.com/inject: "false"
    data-ingest.dynatrace.com/inject: "false"
  container:
    resources:
      requests:
        memory: 5Mi
        cpu: 1m
      limits:
        memory: 10Mi

networkPolicy:
  ## ipBlock configs: this selects particular IP CIDR ranges to allow as egress destinations
  ipBlock:
    ## The External CIDR block that the pod is allowed to connect to
    allowedExtCidr: 0.0.0.0/0
    ## Define an exception list of IP ranges to be excluded from the allowedExtCidr
    blockedCidrs:
      ## Setting this true blocks a default set of CIDR blocks as follows
      ## 100.64.0.0/10, 10.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 127.0.0.0/8 && 192.168.0.0/16
      {{- if (eq "eks" $provider) }}
      defaultBlock: false
      additionalBlockedCidrs:
        - 100.64.0.0/10
        - 169.254.0.0/16
        - 172.16.0.0/12
        - 127.0.0.0/8
        - 192.168.0.0/16
      {{- else }}
      defaultBlock: true
      {{- end }}

  podSelections:
    edge-auth:
      namespace: default
      release: edge-auth
    access-controls:
      namespace: default
      release: access-controls
    feature-flags:
      namespace: default
      release: feature-flags
    keys:
      namespace: default
      release: keys
    licenses:
      namespace: default
      release: licenses
    additionalPodSelections:
      keys:
        release: keys
        namespace: qcs-keys
        port: 8080
