# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main
      - feature/*
      - main_test

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      parameter1: "Value for parameter 1"
      parameter2: "Value for parameter 2"
