# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      parameter1: "Promotion"
      parameter2: "Value for parameter 2"
