# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main
      - feature/*
      - main_test

jobs:
  call_reusable_workflow:
    uses: owner/repo/.github/workflows/reusable-workflow.yml@main  # Reusable workflow reference
    with:
      parameter1: "Value for parameter 1"
      parameter2: "Value for parameter 2"
