# .github/workflows/main-workflow.yml
name: Main Test Workflow

on:
  push:
    branches:
      - main_test

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      parameter1: "Value test 1"
      parameter2: "Value test 2"
