# .github/main-workflows/reusable-workflow.yml 1
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      parameter1:
        description: "First parameter"
        required: true
        type: string
      parameter2:
        description: "Second parameter"
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print parameters
        run: |
          echo "Parameter 1: ${{ inputs.parameter1 }}"
          echo "Parameter 2: ${{ inputs.parameter2 }}"
