# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      parameter1:
        description: "First parameter"
        required: true
        type: string
      parameter2:
        description: "Second parameter"
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print parameters using environment variables
        env:
          PARAM1: ${{ inputs.parameter1 }}
          PARAM2: ${{ inputs.parameter2 }}
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
